### ISSUE TITLE
Error reading configuration file: unrecognized option 'disablewallet'

### ISSUE THREAD

**Issue by bu-tester** [BitcoinUnlimited/BitcoinUnlimited#1013]
If binaries are explicitly built without wallet support, they won't also allow to start the daemon with such setting within it's configuration file (bitcoin.conf)

Eg, if configured as "./configure --disable-wallet", it won't allow later to have "disablewallet=1" on bitcoin.conf. Both bitcoind and bitcoin-qt won't start:

$ cat bitcoin.conf
disablewallet=1

$ bitcoind -daemon
Error reading configuration file: unrecognized option 'disablewallet'

$ bitcoin-qt
Error: Cannot parse configuration file: unrecognized option 'disablewallet'. Only use key=value syntax.

While it's true that builtin support for a wallet is not included in the binaries (per configure flag before make), it should at most be a benign warning, not a fatal error that blocks the daemon start.

Testing builds of multiple binaries under very same data, will fail.

**Comment by sickpig** [comment]
@bu-tester do you think that something like #1342 would be enough?

**Comment by sickpig** [comment]
#1342 partially fix the problem (emit a warning on the console and add a warning to `debug.log`)
