### ISSUE TITLE
You're a load of shit

### ISSUE THREAD

**Issue by jonaschnelli** [BitcoinUnlimited/BitcoinUnlimited#379]
Fuck off, no one wants a hard fork

**Comment by tulip0** [comment]
Note that this is a different account to the Bitcoin Core developer, though they look alike @jonaschnelli is not @jonasschnelli.

**Comment by gandrewstone** [comment]
thanks for mentioning that!  Jonas interacted with us months ago and he was quite kind and polite so I'm happy to learn that this is not him.

**Comment by jonasschnelli** [comment]
Yes. This is not me... will report the user.
My user is written with two s.
