### ISSUE TITLE
Notice of patent infringement

### ISSUE THREAD

**Issue by epowermining** [BitcoinUnlimited/BitcoinUnlimited#492]
This was reported here https://twitter.com/Satoshi_N_/status/858259211356184576

Bitcoin Unlimited violates patent US 20150350171. Please eliminate this code right away so that businesses can safely use Bitcoin Unlimited.

Thank you.

**Comment by GregoryMaxwellIsALiar** [comment]
Could you please explain which lines of code explicitly violent the patent for which reason?

**Comment by sickpig** [comment]
This enquire does not pertain to BU issues tracker.   Closing.

**Comment by epowermining** [comment]
Please reopen this issue. This is an important problem in Bitcoin Unlimited.

The patent violation is at https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/src/secp256k1/src/hash_impl.h#L215

Willful patent infringement is a crime you must fix this as soon as possible.
